---
title: "Project Proposal"
subtitle: "Machine Learning for Public Policy"
author: "Cheng Yee Lim, Rodrigo Valdes-Ortiz, J.Adrián Sánchez"
output:
  pdf_document: default
  html_notebook: default
date: "April, 2017"
---

# Project goals
In light of political and public uproar regarding police-officers using deadly force towards members of the public, our group hopes to reduce these incidents by strengthening the Early Intervention System with machine learning algorithms. 

## Problem definition
The advent of social media has placed the actions of police officers under severe scrutiny. In recent years, there has been videos and pictures of police officers performing adverse actions to civilians circulating online. The circulations of these content has resulted in an incensed public and strained the relationship between the American police force and its civilians.  

## Importance and Impact
Since the goal of the police force is the ensure safety of the civilians, it is important to restore the trust between police and the general public so that the general public can feel "safe" again. 

## Who cares
In the previous administration, the White House has placed public safety, law enforcement and community relations as one of its top priorities. This is evident from the Launch of the Task Force on 21st Century Policing by President Obama in 2015. The goal of the Task Force is to gain a better understanding of specific policing challenges and devise actionable plans to improve law enforcement and enhance community engagement. 

## Who will take action based on your work
The police departments that subscribe to the "Task Force on 21st Century Policing" will take action based on our findings to improve their Early Intervention System. The Charlotte-Mecklenburg Police Department (CMPD) will apply the machine learning algorithms we have devised to improve on their existing Early Intervention System. By detecting police officers at risk of adverse events prior to them committing the action, the CMPD can direct these officers to retraining programmes to extract them from high-stress environments, remind them the ethos of the CMPD and improve on their capacity to deal with such situations. Furthermore, police departments who subscribe to the "Task Force on 21st Century Policing" will also consider the work done for CMPD and build on their own Early Intervention Systems. 

## What are the policy goals you care about?
Leveraging on a more data-driven approach in the Early Intervention System allows the department to better identify police officers at risk, increase internal accountability and reduce inappropriate uses of force. A tangible policy goal we would like achieve through this project is a safer public-facing CMPD, without compromising law enforcement. We also hope to achieve a more intangible goal: to ease the existing tensions and foster stronger trust between the community and the CMPD. 

# Data
The data consists of a detailed event record of each police officer and the officer's demographic information. This extensive dataset has been collected by the CMPD to manage their daily operations. Our outcome variable, adverse events conducted by police officers, is extracted from the incident records when an incident is ruled by the Internal Affairs to be preventable, unjustified and sustained. Other variables of the data include officer dispatch events, criminal complaints made by citizens, traffic stops and arrests made by officers, employee records, secondary employment and neighborhood. 

# Analysis
We are looking to identify a risk ranking score that determines the probability that police officers will engage in adverse event/misconduct behavior^[We refer to adverse events or misconduct behavior for the following criteria: (1) officer's improper use of force, (2) citizen or officer injury or accident and (3) any sustained serious complaint from a citizen or colleague.]. As explained before, our predictors (features) will be **** from a time-period that will predict a risk ranking score which could be used, at different thresholds, to obtain a dummy output variable ${0,1}$ for a top-N list, that indicate if an officer is likely to misbehave in a period of time. 

As the previous section describes, our label (dependent variable) will be based on the 

For this endeavor, we will look to implement three different binary classification models: Logistic Regression, Support Vector Machine (SVM's) and Random Forests. We expect to estimate the probability assigned to class $C_i$ from the three proposed models with distinct parameters settings. 

## What actions will this enable or improve?
The objective of police departments is to train and retain the very highest quality police force. As budget constraints exists, police officers need to train and mentor those that needed the most. In this sense, the objective is to better identify police officers that are riskier to misconduct. By the provision of a score (probability) to each police officer, we could rank police officers by the risk of adverse behavior controlling for precision-recall tradeoffs that can give more control and flexibility to police departments to make interventions such as training, counselling or mentorship that can improve their quality services to the society.
As there are limited resources to intervene all the police force, the ranking allows to the police department to adjust the risk threshold depending on their resources and their capacity to intervene police officers.

# Evaluation
We will train our data for a fixed period of time, 2013-2014, to test in 2015. As we expect that our class of interest is the minority class, accuracy and performance on the majority class are not the right metrics to optimize. For this reason, for assessing the classification performance, we will use precision (true negative rate), the proportion of actual positives among the predicted positives.^[Flach, Peter. Machine learning: the art and science of algorithms that make sense of data. Cambridge University Press, 2012]. We will evaluate the process with a 3-fold cross validation in order to compare the models.

# Policy recommendations.

## Kind of recommendations we hope to give to policymakers
We aim to generate a public policy recommendation for the CMPD. For instance, the objective will be to improve the current system for early interventions. 

The design of this plan will take care that the proposal will be: 1) feasible, within a moderate budget range; 2) better that the actual system (if not, the recommendation is meaningless); 3) political viable, that is to say, that its implementation is realistic given the political constraints.

In specific, the recommendations will be rules to improve their daily operations. For instance, practices like if an officer has been injured two times in the last six months, and has been in two resisted arrests during the past 12 months, assign him to a low-risk area for the next three months. Also, given the limited scope of the project, the recommendations can be design a particular policy for certain officers that we know are at risk. For example, maybe police officers, who are white, between 40 and 50 years old, married, and with more than three arrests related to drugs in the last six months need a particular policy because we know they are at high risk. Specific recommendations need to be discussed with people closer to the daily-basis operations to avoid implausible public policies.

## Validate that our policy will have the desired impact

We can verify our policy in two stages. The first one, before the implementation phase, is run computer simulations with our model to assess the possible results of our recommendations. Then, modify and simplify our recommendation until we produce one with two characteristics: 1) maximize positive results, 2) be feasible and straightforward to operationalize (or the closest to that). At the same time of computer simulations, it will be clue to talk with experts in the field to find reasonable possible outcomes. The effects can be dramatically different of the simulations if we omit key behaviours that experts will know better than us.

The second one is after the application of our public policy. We will validate or implementation against historical data and possible future trends with and without our policy. For instance, one of the methods to evaluate our program will be regression discontinuity to detect structural changes in the patterns before and after the policy. Another way can be, limited to operational and political constraints, make a randomized control experiment with this plan. That is to say, implement the policy in some small subsamples of the population and compare its outcomes with the general ones through econometrics. Then, it will be possible to find it out if the new proposed methodology has the desired impact. Finally, other simple approaches can be implemented, such as compare historical data of the same month, or analyze correlations of incident indicators and relevant variables, like temperature, festivals, vacations days, snow days, or others that can affect the probability of officer's adverse events.